import { IAuthUserData, IErrorField, IFieldObj } from './type/auth-types';
export const countries = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Brunei', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cabo Verde', code: 'CV' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo (Brazzaville)', code: 'CG' },
  { name: 'Congo (Kinshasa)', code: 'CD' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Eswatini', code: 'SZ' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Greece', code: 'GR' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: 'Laos', code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia', code: 'FM' },
  { name: 'Moldova', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'North Korea', code: 'KP' },
  { name: 'North Macedonia', code: 'MK' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russia', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Korea', code: 'KR' },
  { name: 'South Sudan', code: 'SS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syria', code: 'SY' },
  { name: 'Taiwan', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Vatican City', code: 'VA' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

export const accountFields: IFieldObj[] = [
  {
    title: 'Update your Name',
    type: 'firstName',
    inputId: 'first-name',
    inputType: 'text',
    placeholder: 'Enter first name',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    type: 'lastName',
    inputId: 'last-name',
    inputType: 'text',
    placeholder: 'Enter last name',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Choose your date of birth',
    type: 'birthDate',
    inputId: 'birthDate',
    inputType: 'date',
    placeholder: 'Select birth date',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Update your email address',
    type: 'email',
    inputId: 'email',
    inputType: 'email',
    placeholder: 'Enter email',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Set a new password',
    type: 'password',
    inputId: 'password',
    inputType: 'password',
    placeholder: 'Enter password',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
];

export const addressFields: IFieldObj[] = [
  {
    title: 'Enter your street address',
    type: 'street',
    inputId: 'street',
    inputType: 'text',
    placeholder: 'Enter street',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Enter your city',
    type: 'city',
    inputId: 'city',
    inputType: 'text',
    placeholder: 'Enter city',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Enter your postal code',
    type: 'postCode',
    inputId: 'postcode',
    inputType: 'text',
    placeholder: 'Enter postal code',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Select your country',
    type: 'country',
    inputId: 'country',
    inputType: 'select',
    placeholder: 'Select country',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
];

export const shippingFields: IFieldObj[] = [
  {
    title: 'Enter shipping street address',
    type: 'shippingStreet',
    inputId: 'shipping-street',
    inputType: 'text',
    placeholder: 'Enter shipping street',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Enter shipping city',
    type: 'shippingCity',
    inputId: 'shipping-city',
    inputType: 'text',
    placeholder: 'Enter shipping city',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Enter shipping postal code',
    type: 'shippingPostCode',
    inputId: 'shipping-postcode',
    inputType: 'text',
    placeholder: 'Enter shipping postal code',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
  {
    title: 'Select shipping country',
    type: 'shippingCountry',
    inputId: 'shipping-country',
    inputType: 'select',
    placeholder: 'Select shipping country',
    classNameInput: 'create-account__input',
    classNameItem: 'create-account__input-item',
    classNameWarning: 'input-item-warning',
  },
];

export const errorFields: IErrorField[] = [
  { key: 'firstName', message: 'Please enter your first name' },
  { key: 'lastName', message: 'Please enter your last name' },
  { key: 'birthDate', message: 'please chose your date birth' },
  { key: 'email', message: 'Please enter your email' },
  { key: 'password', message: 'Please enter your password' },

  { key: 'street', message: 'Please enter your street' },
  { key: 'city', message: 'Please enter your city' },
  { key: 'postCode', message: 'Please enter your postal code' },
  { key: 'country', message: 'Please chose your country' },

  { key: 'shippingStreet', message: 'Please enter your shipping street' },
  { key: 'shippingCity', message: 'Please enter your shipping city' },
  {
    key: 'shippingPostCode',
    message: 'Please enter your shipping postal code',
  },
  { key: 'shippingCountry', message: 'Please choose your shipping country' },
];

export const validationData = [
  {
    type: 'firstName',
    err: 'First name: Must contain at least one character and no special characters or numbers',
    isValid: (value: string): boolean => value.length > 0,
  },

  {
    type: 'lastName',
    err: 'Last name: Must contain at least one character and no special characters or numbers',
    isValid: (value: string): boolean => value.length > 0,
  },

  {
    type: 'birthDate',
    err: 'Date of birth: A valid date input ensuring the user is above a certain age (e.g., 13 years old or older)',
    isValid: (value: string): boolean =>
      /^(19\d{2}|200\d|201[0-2])-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/.test(
        value
      ),
  },

  {
    type: 'email',
    err: 'Email: A properly formatted email address (e.g., example@email.com)',
    isValid: (value: string): boolean =>
      /^[^\s@]+@[^\s@]+\.[a-zA-Z]{2,}$/.test(value),
  },

  {
    type: 'password',
    err: 'Password: Minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter, and 1 number',
    isValid: (value: string): boolean =>
      /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/.test(value),
  },

  {
    type: 'street',
    err: 'Street: Must contain at least one character',
    isValid: (value: string): boolean => value.length > 0,
  },

  {
    type: 'city',
    err: 'City: Must contain at least one character and no special characters or numbers',
    isValid: (value: string): boolean => value.length > 0,
  },

  {
    type: 'postCode',
    err: 'Postal code: Must follow the format for the country (e.g., 12345 or A1B 2C3 for the U.S. and Canada, respectively)',
    isValid: (value: string): boolean => /^[A-Za-z0-9\s-]{3,10}$/.test(value),
  },

  {
    type: 'country',
    err: 'There isn`t such country',
    isValid: (value: string): boolean => value.length > 0,
  },

  {
    type: 'shippingStreet',
    err: 'Street: Must contain at least one character',
    isValid: (value: string): boolean => value.length > 0,
  },

  {
    type: 'shippingCity',
    err: 'City: Must contain at least one character and no special characters or numbers',
    isValid: (value: string): boolean => value.length > 0,
  },

  {
    type: 'shippingPostCode',
    err: 'Postal code: Must follow the format for the country (e.g., 12345 or A1B 2C3 for the U.S. and Canada, respectively)',
    isValid: (value: string): boolean => /^[A-Za-z0-9\s-]{3,10}$/.test(value),
  },

  {
    type: 'shippingCountry',
    err: 'There isn`t such country',
    isValid: (value: string): boolean => value.length > 0,
  },
];

export const authUserData: IAuthUserData = {
  newUser: {
    firstName: undefined,
    lastName: undefined,
    birthDate: '2000-01-01',
    email: undefined,
    password: undefined,

    street: undefined,
    city: undefined,
    postCode: undefined,
    country: undefined,

    shippingStreet: undefined,
    shippingCity: undefined,
    shippingPostCode: undefined,
    shippingCountry: undefined,
  },

  addressDefaults: {
    isBillingAddressDef: false,
    isShippingAddress: false,
  },

  logIn: {
    email: undefined,
    password: undefined,
  },

  restorUser: {
    email: undefined,
  },
};

export const defaultCopyAuthUserData: IAuthUserData =
  structuredClone(authUserData);
